package com.chelsenok.translator.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "TRANSLATION_RESULT".
 */
@Entity
public class TranslationResult {

    @Id
    private Long id;
    private String nativeSentence;
    private String foreignSentence;
    private String nativeShortcut;
    private String foreignShortcut;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public TranslationResult() {
    }

    public TranslationResult(Long id) {
        this.id = id;
    }

    @Generated
    public TranslationResult(Long id, String nativeSentence, String foreignSentence, String nativeShortcut, String foreignShortcut) {
        this.id = id;
        this.nativeSentence = nativeSentence;
        this.foreignSentence = foreignSentence;
        this.nativeShortcut = nativeShortcut;
        this.foreignShortcut = foreignShortcut;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNativeSentence() {
        return nativeSentence;
    }

    public void setNativeSentence(String nativeSentence) {
        this.nativeSentence = nativeSentence;
    }

    public String getForeignSentence() {
        return foreignSentence;
    }

    public void setForeignSentence(String foreignSentence) {
        this.foreignSentence = foreignSentence;
    }

    public String getNativeShortcut() {
        return nativeShortcut;
    }

    public void setNativeShortcut(String nativeShortcut) {
        this.nativeShortcut = nativeShortcut;
    }

    public String getForeignShortcut() {
        return foreignShortcut;
    }

    public void setForeignShortcut(String foreignShortcut) {
        this.foreignShortcut = foreignShortcut;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
